name: "CI/CD"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

    types:
      - closed

jobs:
  build-and-test:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Use Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Build & Run Go'
        run: |
          go build -o main go-service/main.go
          ./main &
          sleep 5

      - name: 'Test Go'
        run: curl localhost:8080
      
      - name: 'Kill Go Service'
        run: killall main

      - name: 'Build & Run Node.js'
        run: |
          ls

      - name: 'Test Go'
        run: curl localhost:8080
          
      

    
    

