name: "CI/CD"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

    types:
      - closed

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Build & Run Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        run: |
          go build -o go-service go-service/go-service.go
          ./go-service &
          sleep 5

      - name: 'Test Go'
        run: curl localhost:8080
          
      

    
    

