name: "CI/CD"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

    types:
      - closed

jobs:
  build-and-test:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Use Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Build & Run Go'
        run: |
          go build -o main go-service/main.go
          ./main &
          sleep 5

      - name: 'Test Go'
        run: curl localhost:8080
      
      - name: 'Kill Go Service'
        run: killall main

      - name: 'Build & Run Node.js'
        working-directory: ./node-service
        run: |
          npm install
          node service.js &
          sleep 5

      - name: 'Test Node.js'
        run: curl localhost:8080
          
      - name: 'Kill Node.js process'
        run: |
          pkill -f service.js

  build-image:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Docker Hub Authentication'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: 'Docker Image Build Go'
        working-directory: ./go-service
        run: docker build -t yogatrista/sre-test-pintu:go .

      - name: 'Docker Image Build Node.js'
        working-directory: ./node-service
        run: docker build -t yogatrista/sre-test-pintu:node .

      - name: 'Docker Go Push to Docker Hub'
        run: docker push yogatrista/sre-test-pintu:go

      - name: 'Docker Node.js Push to Docker Hub'
        run: docker push yogatrista/sre-test-pintu:node